python VN_test.py \
--dataroot data/datasets/VN_train \
--ttfRoot data/fonts/VN/arial.ttf \
--corpusRoot /mnt/disk3/vietocr/datasets/labels/47_words.txt \
--name VN_handwriting_arial \
--model handwritten \
--imgH 64 \
--imgW 384 \
--G_ch 64 \
--gpu_ids 1 \
--num_threads 20